[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pda_1_d = "4jiaRCGfD5YLTfWeAPDP9hwW6a9P1ZXF4uH66v1BXQT4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
